version: '2'

networks:
  hf-exp:

services:

  zookeeper0:
    extends:
      file: docker-kafka.yaml
      service: zookeeper
    container_name: zookeeper0
    hostname: zookeeper0
    environment:      
      - ZOO_MY_ID=1      
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - hf-exp

  zookeeper1:
    extends:
      file: docker-kafka.yaml
      service: zookeeper
    container_name: zookeeper1
    hostname: zookeeper1
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - hf-exp

  zookeeper2:
    extends:
      file: docker-kafka.yaml
      service: zookeeper
    container_name: zookeeper2
    hostname: zookeeper2
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - hf-exp

  kafka0:
    extends:
      file: docker-kafka.yaml
      service: kafka
    container_name: kafka0
    hostname: kafka0
    environment:      
      - KAFKA_BROKER_ID=0      
      - KAFKA_MIN_INSYNC_REPLICAS=2      
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3      
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181      
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2    
    networks:
      - hf-exp

  kafka1:
    extends:
      file: docker-kafka.yaml
      service: kafka
    container_name: kafka1
    hostname: kafka1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2    
    networks:
      - hf-exp

  kafka2:
    extends:
      file: docker-kafka.yaml
      service: kafka
    container_name: kafka2
    hostname: kafka2
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2  
    networks:
      - hf-exp  

  kafka3:
    extends:
      file: docker-kafka.yaml
      service: kafka
    container_name: kafka3
    hostname: kafka3
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2   
    networks:
      - hf-exp 

  orderer.ksachdeva-exp.com:    
    container_name: orderer.ksachdeva-exp.com
    extends:
      file:  docker-compose-orderer.yaml
      service: orderer.ksachdeva-exp.com
    volumes:
      - ./genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/ksachdeva-exp.com/orderers/orderer.ksachdeva-exp.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/ksachdeva-exp.com/orderers/orderer.ksachdeva-exp.com/tls/:/var/hyperledger/orderer/tls
      - ./production:/var/hyperledger/production
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3  
    links:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - hf-exp

  peer1.org1.ksachdeva-exp.com:
    container_name: peer1.org1.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer1.org1.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org1-peer1:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org1.ksachdeva-exp.com/peers/peer1.org1.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.ksachdeva-exp.com/peers/peer1.org1.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - hf-exp

  peer0.org2.ksachdeva-exp.com:
    container_name: peer0.org2.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer0.org2.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org2-peer0:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer0.org2.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer0.org2.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - hf-exp

  peer1.org2.ksachdeva-exp.com:
    container_name: peer1.org2.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer1.org2.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org2-peer1:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer1.org2.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer1.org2.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      - hf-exp

  peer0.org3.ksachdeva-exp.com:
    container_name: peer0.org3.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer0.org3.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org3-peer0:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer0.org3.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer0.org3.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - hf-exp

  peer1.org3.ksachdeva-exp.com:
    container_name: peer1.org3.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer1.org3.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org3-peer2:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer1.org3.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer1.org3.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12053:7053
    networks:
      - hf-exp